version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresLMS
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
