// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package orm

import (
	"database/sql"
	"time"
)

type Book struct {
	BookID          int32          `json:"book_id"`
	Title           string         `json:"title"`
	Authors         string         `json:"authors"`
	Publisher       sql.NullString `json:"publisher"`
	PublicationDate sql.NullTime   `json:"publication_date"`
	Genre           sql.NullString `json:"genre"`
	Description     sql.NullString `json:"description"`
	Language        sql.NullString `json:"language"`
	Edition         sql.NullInt32  `json:"edition"`
	NumCopies       sql.NullInt32  `json:"num_copies"`
	Location        sql.NullString `json:"location"`
	ImageUrl        sql.NullString `json:"image_url"`
	Keywords        sql.NullString `json:"keywords"`
}

type Borrowedbook struct {
	BorrowedID   int32        `json:"borrowed_id"`
	UserID       int32        `json:"user_id"`
	BookID       int32        `json:"book_id"`
	BorrowedDate time.Time    `json:"borrowed_date"`
	ReturnedDate sql.NullTime `json:"returned_date"`
	DueDate      sql.NullTime `json:"due_date"`
}

type User struct {
	UserID        int32          `json:"user_id"`
	Email         string         `json:"email"`
	Firstname     string         `json:"firstname"`
	Lastname      string         `json:"lastname"`
	ContactNumber sql.NullString `json:"contact_number"`
	Address       string         `json:"address"`
}
